package types;

public enum GlobalReligion {
	catholic          ,
	orthodox          ,
	miaphysite        ,
	nestorian         ,
	sunni             ,
	ibadi             ,
	shiite            ,
	zoroastrian       ,
	jewish            ,
	hindu             ,
	buddhist          ,
	jain		,
	cathar     ,
	fraticelli ,
	waldensian ,
	lollard    ,
	monophysite,
	bogomilist ,
	monothelite,
	iconoclast ,
	paulician  ,
	messalian  ,
	zikri      ,
	yazidi     ,
	kharijite  ,
	druze      ,
	hurufi     ,
	mazdaki    ,
	manichean  ,
	samaritan  ,
	karaite			,
	pagan             ,
	norse_pagan       ,
	tengri_pagan      ,
	baltic_pagan      ,
	finnish_pagan     ,
	aztec             ,
	slavic_pagan      ,
	west_african_pagan,
	zun_pagan         ,
	hellenic_pagan  
}
